# Generated by Django 5.2.1 on 2025-06-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("consultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationinterest",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
